#!/usr/bin/env node
/**
 * build-index.js — auto-detect subpages in hitthe.link and regenerate
 * the project grid in index.html.
 *
 * Scans every top-level dir for index.html, extracts <title> + meta description,
 * then renders the project cards inside the <!-- AUTO:PROJECTS:START --> /
 * <!-- AUTO:PROJECTS:END --> markers in index.html. If markers are absent,
 * appends them as a section above </body>.
 *
 * Run: node build-index.js
 * Optional pre-commit hook: ln -s build-index.js .git/hooks/pre-commit (after chmod +x)
 *
 * Per qi 2026-05-21: "To auto detect new subpages" — index.html stops being
 * hand-curated; subdirs become the source of truth.
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const INDEX_PATH = path.join(ROOT, 'index.html');
// qi 2026-06-05: NOTHING HIDDEN. Every page shows in the root index — full count.
// Only genuine non-page infra is skipped. elios is just a redirect stub to /eliops,
// kept out to avoid a duplicate card; eliops itself IS shown.
const SKIP_DIRS = new Set([
  '.git', '.github', 'node_modules', '_shared', 'browser', 'icons',
  'elios', // redirect stub -> /eliops (avoid duplicate card)
  'xen-map', // internal Xen/Exedus architecture map — noindex, not for public grid
  'debt', // internal Xen Ledger — noindex, not for public grid
  'vision', // omni vision wall — qi's private device screens, noindex, never public
  'hooks', // webhook control surface — qi's private pane-%0 webhook console, noindex
]);
// Friendly URL overrides: card href + slug display uses alias, actual dir stays canonical
const SLUG_ALIAS = {
  'eliops': 'elios',
};

function extractMeta(htmlPath) {
  const html = fs.readFileSync(htmlPath, 'utf8');
  const titleMatch = html.match(/<title>([^<]+)<\/title>/i);
  const descMatch = html.match(/<meta\s+name=["']description["']\s+content=["']([^"']+)["']/i);
  const ogTitleMatch = html.match(/<meta\s+property=["']og:title["']\s+content=["']([^"']+)["']/i);
  const ogDescMatch = html.match(/<meta\s+property=["']og:description["']\s+content=["']([^"']+)["']/i);
  const iconSvg = fs.existsSync(path.join(path.dirname(htmlPath), 'icon.svg'));
  const iconPng = fs.existsSync(path.join(path.dirname(htmlPath), 'icon.png'));
  return {
    title: (ogTitleMatch?.[1] || titleMatch?.[1] || path.basename(path.dirname(htmlPath))).trim(),
    description: (ogDescMatch?.[1] || descMatch?.[1] || '').trim(),
    hasIcon: iconSvg || iconPng,
    iconHref: iconSvg ? 'icon.svg' : (iconPng ? 'icon.png' : null),
  };
}

const subpages = [];
for (const entry of fs.readdirSync(ROOT, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  if (entry.name.startsWith('.')) continue;
  if (SKIP_DIRS.has(entry.name)) continue;
  const idx = path.join(ROOT, entry.name, 'index.html');
  if (!fs.existsSync(idx)) continue;
  try {
    const meta = extractMeta(idx);
    subpages.push({
      slug: entry.name,
      ...meta,
    });
  } catch (e) {
    console.warn(`skip ${entry.name}: ${e.message}`);
  }
}

subpages.sort((a, b) => a.slug.localeCompare(b.slug));

console.log(`detected ${subpages.length} subpages`);

const cards = subpages.map(s => {
  const link = SLUG_ALIAS[s.slug] || s.slug;
  return `      <a href="/${link}/" class="project-card group">
        <div class="card-head">
          ${s.iconHref ? `<img src="/${s.slug}/${s.iconHref}" alt="" class="card-icon" loading="lazy">` : `<div class="card-icon-placeholder"></div>`}
          <h3 class="card-title">${escapeHtml(s.title)}</h3>
        </div>
        ${s.description ? `<p class="card-desc">${escapeHtml(s.description)}</p>` : ''}
        <span class="card-slug">/${link}/</span>
      </a>`;
}).join('\n');

const block = `<!-- AUTO:PROJECTS:START -->
    <section class="auto-projects" aria-label="All projects (auto-detected)">
      <h2 class="auto-projects-heading">All Projects · ${subpages.length} subpages</h2>
      <div class="auto-projects-grid">
${cards}
      </div>
      <p class="auto-projects-meta">Generated by <code>build-index.js</code> at ${new Date().toISOString()} — every subdir with an <code>index.html</code> appears here automatically.</p>
    </section>
    <style>
      .auto-projects { padding: 48px 24px; max-width: 1280px; margin: 0 auto; }
      .auto-projects-heading { font-size: 14px; letter-spacing: 0.15em; text-transform: uppercase; color: rgba(255,255,255,0.5); margin: 0 0 24px; }
      .auto-projects-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 12px; }
      .project-card { display: block; padding: 16px; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; text-decoration: none; color: inherit; transition: all 0.18s ease; }
      .project-card:hover { background: rgba(255,255,255,0.06); border-color: var(--theme-color, #D4AF37); transform: translateY(-2px); }
      .card-head { display: flex; align-items: center; gap: 12px; margin-bottom: 8px; }
      .card-icon, .card-icon-placeholder { width: 28px; height: 28px; border-radius: 6px; object-fit: contain; flex-shrink: 0; }
      .card-icon-placeholder { background: linear-gradient(135deg, rgba(212,175,55,0.2), rgba(31,95,63,0.2)); }
      .card-title { font-size: 14px; font-weight: 600; margin: 0; color: #fff; }
      .card-desc { font-size: 12px; color: rgba(255,255,255,0.65); margin: 0 0 8px; line-height: 1.4; max-height: 3.6em; overflow: hidden; }
      .card-slug { font-family: ui-monospace, 'SF Mono', monospace; font-size: 11px; color: rgba(255,255,255,0.4); }
      .auto-projects-meta { font-size: 11px; color: rgba(255,255,255,0.3); margin-top: 24px; font-family: ui-monospace, 'SF Mono', monospace; }
    </style>
<!-- AUTO:PROJECTS:END -->`;

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
}

let html = fs.readFileSync(INDEX_PATH, 'utf8');
const start = '<!-- AUTO:PROJECTS:START -->';
const end = '<!-- AUTO:PROJECTS:END -->';
const startIdx = html.indexOf(start);
const endIdx = html.indexOf(end);

if (startIdx !== -1 && endIdx !== -1) {
  html = html.slice(0, startIdx) + block + html.slice(endIdx + end.length);
  console.log('replaced existing AUTO:PROJECTS block');
} else {
  // Insert before </body>
  const bodyClose = html.lastIndexOf('</body>');
  if (bodyClose === -1) {
    console.error('no </body> tag found');
    process.exit(1);
  }
  html = html.slice(0, bodyClose) + '\n' + block + '\n' + html.slice(bodyClose);
  console.log('inserted new AUTO:PROJECTS block before </body>');
}

fs.writeFileSync(INDEX_PATH, html);
console.log(`wrote ${INDEX_PATH} with ${subpages.length} project cards`);
